// Generated by CoffeeScript 1.11.1
(function() {
  var should, stringToArray;

  stringToArray = require('../lib/string-to-array.js');

  should = require('should');

  describe('string-to-array', function() {
    return it('should be defined', function() {});
  });

}).call(this);
